version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: rest_app
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
    volumes:
      - type: bind
        source: ./bd_data
        target: /var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080