"""Init

Revision ID: e2f540d91738
Revises: 
Create Date: 2024-04-07 18:53:31.367121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f540d91738'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_email'), 'records', ['email'], unique=False)
    op.create_index(op.f('ix_records_first_name'), 'records', ['first_name'], unique=False)
    op.create_index(op.f('ix_records_last_name'), 'records', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_last_name'), table_name='records')
    op.drop_index(op.f('ix_records_first_name'), table_name='records')
    op.drop_index(op.f('ix_records_email'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
